{
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
        "ID": "CVE-2021-3422",
        "STATE": "PUBLIC",
        "ASSIGNER": "prodsec@splunk.com",
        "TITLE": "Indexer denial-of-service via malformed S2S request"
    },
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "vendor_name": "Splunk",
                    "product": {
                        "product_data": [
                            {
                                "product_name": "Splunk Enterprise",
                                "version": {
                                    "version_data": [
                                        {
                                            "version_value": "8.2 version(s) before 8.2.0"
                                        },
                                        {
                                            "version_value": "8.1 version(s) before 8.1.3"
                                        },
                                        {
                                            "version_value": "8.0 version(s) before 8.0.9"
                                        },
                                        {
                                            "version_value": "7.3 version(s) before 7.3.9"
                                        }
                                    ]
                                }
                            }
                        ]
                    }
                }
            ]
        }
    },
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "CWE-125 Out-of-bounds Read"
                    }
                ]
            }
        ]
    },
    "references": {
        "reference_data": [
            {
                "url": "https://www.splunk.com/en_us/product-security/announcements/svd-2022-0301.html",
                "refsource": "MISC",
                "name": "https://www.splunk.com/en_us/product-security/announcements/svd-2022-0301.html"
            },
            {
                "url": "https://claroty.com/2022/03/24/blog-research-locking-down-splunk-enterprise-indexers-and-forwarders/2",
                "refsource": "MISC",
                "name": "https://claroty.com/2022/03/24/blog-research-locking-down-splunk-enterprise-indexers-and-forwarders/2"
            }
        ]
    },
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "The lack of validation of a key-value field in the Splunk-to-Splunk protocol results in a denial-of-service in Splunk Enterprise instances configured to index Universal Forwarder traffic. See https://docs.splunk.com/Documentation/Splunk/latest/Forwarding/Enableareceiver for more information on configuring an indexer to listen for UF traffic. It does not impact Universal Forwarders. When Splunk forwarding is secured using TLS or a Token, the attack requires compromising the certificate or token, or both. As a partial mitigation and a security best practice, see https://docs.splunk.com/Documentation/Splunk/latest/Security/ConfigureSplunkforwardingtousesignedcertificates and https://docs.splunk.com/Documentation/Forwarder/latest/Forwarder/Controlforwarderaccess. Implementation of either or both reduces the severity to Medium."
            }
        ]
    },
    "impact": {
        "cvss": {
            "baseScore": "7.5",
            "vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
            "version": "3.1"
        }
    },
    "credit": [
        {
            "lang": "eng",
            "value": "Sharon Brizinov and Tal Keren of Claroty"
        }
    ],
    "generator": {
        "engine": "advisoriator"
    },
    "source": {
        "advisory": "SVD-2022-0301",
        "discovery": "EXTERNAL"
    }
}